### ISSUE TITLE
fucking bazharapple

### ISSUE THREAD

**Issue by ytmcgamer** [solar1337/appleloader-source#2]
this is a fucking valorant loader and its from bazhar made for apple niggr i leaked it first but ok no credits thx

**Comment by solar1337** [comment]
see the source code its not the valorant loader

Le sam. 26 sept. 2020 à 16:40, YTMcGamer <notifications@github.com> a
écrit :

**Comment by ytmcgamer** [comment]
then why is there a file named valorant big brain when its an fortnite loader https://github.com/solar1337/appleloader-source/blob/master/valorent.cpp

**Comment by ytmcgamer** [comment]
https://github.com/solar1337/appleloader-source/blob/master/valorent.cpp#L43 
it says  Apple VALORANT  fortnite loader right?

**Comment by ytmcgamer** [comment]
...
